# Generated by Django 5.2.15 on 2026-07-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_seed_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishitem',
            name='analytics_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishitem',
            name='automation_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishitem',
            name='external_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publishitem',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publishitem',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishitem',
            name='platform_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='publishitem',
            name='publish_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publishitem',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
