# Generated by Django 5.2.15 on 2026-06-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.CharField(default='Blank', max_length=50),
        ),
    ]
