# Generated by Django 5.2.15 on 2026-07-01 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_project_project_progress_projectactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('excerpt', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('favorite', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(default=0)),
                ('reading_time', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6366f1', max_length=50)),
                ('template', models.CharField(default='Blank', max_length=50)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='productivity.project')),
            ],
            options={
                'ordering': ['-pinned', '-favorite', '-updated_at'],
            },
        ),
    ]
