# Generated by Django 5.2.15 on 2026-07-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0008_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
