# Generated by Django 5.2.15 on 2026-07-07 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0009_calendarevent_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('excerpt', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Review', 'Review'), ('Published', 'Published')], default='Draft', max_length=50)),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Workspace', 'Workspace')], default='Private', max_length=50)),
                ('cover_image', models.CharField(blank=True, default='', max_length=500)),
                ('template', models.CharField(default='Blank', max_length=50)),
                ('word_count', models.IntegerField(default=0)),
                ('reading_time', models.IntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='productivity.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
