# Generated by Django 5.2.15 on 2026-07-13 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0011_document_archived'),
        ('publishing', '0002_seed_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='related_publish_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='publishing.publishitem'),
        ),
    ]
