# Generated by Django 5.2.15 on 2026-07-10 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productivity', '0011_document_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('asset_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Audio', 'Audio'), ('PDF', 'PDF'), ('Logo', 'Logo'), ('Thumbnail', 'Thumbnail'), ('Document', 'Document'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=500)),
                ('storage_path', models.CharField(max_length=500)),
                ('favorite', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='productivity.project')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='productivity.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
