# Generated by Django 5.2.15 on 2026-07-10 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0001_initial'),
        ('productivity', '0011_document_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='related_calendar_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='productivity.calendarevent'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='related_knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='productivity.knowledgeitem'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='related_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='productivity.note'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='productivity.task'),
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='creative.mediafolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_folders', to='productivity.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='creative.mediafolder'),
        ),
    ]
